### PR TITLE
added server file and modified codeclock to do scraping in backend

### LINKED ISSUE #5: Convert the matplotlib obtained after training ML model to HTML using mpld3
Just convert the matplotlib data obtained after using ML Model to a HTML script and then embed it into the webpage. Pretty simple.

NOTE: Make sure to complete the previous steps - Training the ML Model issue and Obtaining dataset issue before moving onto this issue.

### LINKED ISSUE #11: Using python web scrapers present in Scrappers folder, automate codeclock.html (from static to dynamic webpage)
Basically codeclock.html contains the date and time of upcoming contests on Codeforces, Atcoder, Codechef and Leetcode.

I want someone to automate this process:

The process: 
1) Fetch details of upcoming competitive programming contests from four websites - Codeforces, AtCoder, CodeChef and Leetcode.
(Already done and present in repo)

2) These details have been fetched using Codeforces API for Codeforces and Web Scrapers for AtCoder, CodeChef and Leetcode. (Already done and present in repo)

3) I want someone to edit codeclock.html and use JavaScript or some other backend to run the python webscrapers, fetch the details obtained from the python scripts and dynamically put it inside codeclock.html (previously these values were getting stored in csv file) and I have to manually put the data inside the div tag which is time consuming and static in nature.

This issue basically wants one to fix the 3) point. Basically just automate the process which was static earlier to dynamic. DONE!

### PR DESCRIPTION
**Pull request by HavokSahil**
Automated Codeclock.html
closes #11 
closes #5 
Procedures:
```cd Server```
```python cclock_server.py```

> Then open codeclock.html

Following is the result
image

Issues:
The LeetCode scraper in the Scrapers folder wasn't working.

### CODE REVIEW

**Comment by re4lvanshsingh** [comment]
@HavokSahil The Leetcode scraper was working for me last time I checked. You sure?

**Comment by HavokSahil** [comment]
@re4lvanshsingh I have checked it coupe of times. Can you verify if its running now?

**Comment by HavokSahil** [comment]
@re4lvanshsingh 
I have modified the about the about.html to show the updated plot
#5 
image

**Comment by re4lvanshsingh** [comment]
@HavokSahil Fine I will look into Leetcode later. Merged

**Pull request merged**
